config/routes.rb
Rails.application.routes.draw do
  
  resources :dashboard, only: [:show]
  get 'report', to: 'report#index'

  resources :sessions, only: [:new, :create, :destroy]

  get 'user/farms', to: 'farms#user_show'
  post '/weather/forecast', to: 'weather_logs#get_weather'
  # get 'user/report', to: 'report#show'

  resources :weather_logs
  resources :sub_farm_activities
  resources :stocks
  resources :resources
  
  resources :crops
  resources :farms do
    resources :sub_farms
  end

  resources :users

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/farm.rb
class Farm < ApplicationRecord
  belongs_to :user
  has_many :sub_farms, dependent: :destroy
  has_many :stock
  has_many :sub_farm_activities, through: :sub_farms

  validates :name, presence: true
  validates :user_id, presence: true
  validates :size, numericality: true

  def last_activities
    sub_farm_activities.order("activity_id, date DESC").select("DISTINCT ON(activity_id) *")
  end

  private

  def last_watered
    sub_farm_activities.order("activity_id, date DESC").select("DISTINCT ON(activity_id) *")
  end

  def last_fertilized
    sub_farm_activities.order("activity_id, date DESC").select("DISTINCT ON(activity_id) *")
  end

  def last_chemicalled
    sub_farm_activities.order("activity_id, date DESC").select("DISTINCT ON(activity_id) *")
  end

  # def last_watered
  #   @water_activity = sub_farm_activities.where(activity_id: 1).select("DISTINCT ON(sub_farm_id)*").order("sub_farm_id, date DESC")
  # end

  # def last_fertilized
  #   @fertilizer_activity = sub_farm_activities.where(activity_id: 2).select("DISTINCT ON(sub_farm_id)*").order("sub_farm_id, date DESC")
  # end

  # def last_chemicalled
  #   @chemical_activity = sub_farm_activities.where(activity_id: 3).select("DISTINCT ON(sub_farm_id)*").order("sub_farm_id, date DESC")
  # end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show, :edit, :update, :destroy]

  def user_show
    @farms = Farm.where(user_id: current_user.id)
    render :index
  end

  # GET /farms
  # GET /farms.json
  def index
    @farms = Farm.all
  end

  # GET /farms/1
  # GET /farms/1.json
  def show
    @farm = Farm.find(params[:id])
    @sub_farms = @farm.sub_farms
  end

  # GET /farms/new
  def new
    @farm = Farm.new
  end

  # GET /farms/1/edit
  def edit
  end

  # POST /farms
  # POST /farms.json
  def create
    @farm = Farm.new(farm_params)
    @farm.user_id = current_user.id

    respond_to do |format|
      if @farm.save
        format.html { redirect_to @farm, notice: 'Farm was successfully created.' }
        format.json { render :show, status: :created, location: @farm }
      else
        format.html { render :new }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /farms/1
  # PATCH/PUT /farms/1.json
  def update
    respond_to do |format|
      if @farm.update(farm_params)
        format.html { redirect_to @farm, notice: 'Farm was successfully updated.' }
        format.json { render :show, status: :ok, location: @farm }
      else
        format.html { render :edit }
        format.json { render json: @farm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /farms/1
  # DELETE /farms/1.json
  def destroy
    @farm.destroy
    respond_to do |format|
      format.html { redirect_to user_farms_url, notice: 'Farm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_farm
      @farm = Farm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def farm_params
      params.require(:farm).permit(:name, :farm_code, :lat, :lng, :layout, :size)
    end
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/views/farms/_form.html.erb
<div class="container-fluid new-farm">
  <div class="row">
    <div class="col-md-6" id="map">
      <!-- <div id="map" class="center-block"></div> -->
    </div>
    <div class="col-md-6 text-left">

      <%= form_for(farm) do |f| %>
        <% if farm.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(farm.errors.count, "error") %> prohibited this farm from being saved:</h2>

            <ul>
            <% farm.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <table class="table">

        <tr>
          <td>
            <%= f.label :name %>
          </td>
          <td>
            <%= f.text_field :name, class: "form-control" %>
          </td>
        </tr>

        <tr>
        <td>
          <%= f.label :farm_code, "Farm code (Optional)" %>
          </td>
          <td>
          <%= f.text_field :farm_code, class: "form-control" %>
        </td>
        </tr>

        <tr>
        <td>
          <%= f.label :size, "Size (ha)" %>
          </td>
          <td>
          <%= f.text_field :size, class: "form-control" %>
          </td>
        
        </tr>

        </table>

        <p>* please drag <i class="fa fa-map-marker fa-2x" aria-hidden="true"></i> on to your farm location</p>
        <table class="table">
        <tr>
        <td class="field input-lat" id="input-lat">
          <%= f.label :lat, "Latitude" %>
          </td>
          <td>
          <%= f.text_field :lat, class: "form-control", readonly: true %>
          </td>
        
        </tr>

        <tr>
          <td class="field input-lng">
            <%= f.label :lng, "Longitude" %>
          </td>
          <td>
            <%= f.text_field :lng, class: "form-control", readonly: true %>
          </td>
        </tr>

        </table>

        <div class="actions text-center">
          <%= f.submit 'Create', class: "btn" %>
          <%= link_to 'Cancel', user_farms_path, class: "btn cancel" %>
        </div>
      <% end %>
    </div>
  </div>
</div>



<!-- <div id="map" class="center-block"></div> -->



<script>
  var map;
  var marker;
  var geocoder;
  var infowindow;

  function initMap() {
    geocoder = new google.maps.Geocoder();

    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 4.5076156, lng: 114.4846021},
      zoom: 10
    });

    marker = new google.maps.Marker({
      map: map,
      draggable: true,
      animation: google.maps.Animation.DROP,
      position: {lat: 4.5076156, lng: 114.4846021}
    });
    // marker.addListener('click', toggleBounce);

    infowindow = new google.maps.InfoWindow({
      content: 'contentString'
    });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });

    marker.addListener('dragend', function (evt) {
      console.log(evt.latLng.lat() + ' ' + evt.latLng.lng());

      $('#farm_lat').val(evt.latLng.lat());
      $('#farm_lng').val(evt.latLng.lng());

      geocodePosition(marker.getPosition());

    
    });

  }


  function geocodePosition(pos) {
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
      infowindow.setContent(responses[0].formatted_address);
    } else {
      infowindow.setContent('Cannot determine address at this location.');
    }
  });
}
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GGMAP_APP_KEY'] %>
&callback=initMap"
async defer></script>

app/views/farms/edit.html.erb
<main id="farm-index" class="container text-center">

  <div class="row header-container">
    <div class='col-md-12'>
      <h1>Edit Farm</h1>
    </div>
  </div>

  <div class="row content-container">
    <div class="col-md-12">
      <%= render 'form', farm: @farm %>

    </div>
  </div>


</main>

app/views/farms/index.html.erb
<section id="farm-index" class="container">
  <div class="row header-container">
    <div class='col-md-12'>
      <h1>Your Farms</h1>
    </div>
  </div>


<div class="row content-container">

  <div class="col-md-6" id="map">
    <!-- <div id="map"></div> -->
  </div>

  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Farm code</th>
          <th>Size (ha)</th>
          <th>Subfarms</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @farms.each do |farm| %>
          <tr>
            <td><%= farm.name %></td>
            <td><%= farm.farm_code %></td>
            <td><%= farm.size %></td>
            <td><%= farm.sub_farms.count %></td>
            <td><%= link_to raw('<i class="fa fa-eye" aria-hidden="true"></i>'), farm, title: "Show" %></td>
            <td><%= link_to raw('<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'), edit_farm_path(farm), title: "Edit" %></td>
            <td><%= link_to raw('<i class="fa fa-trash" aria-hidden="true"></i>'), farm, method: :delete, data: { confirm: 'Are you sure?' }, title: "Delete" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <div class="text-center">
      <%= link_to 'New Farm', new_farm_path, class: "btn" %>
    </div>
    <br>
  </div>
</div>


</section>



<script>
  var map;
  var markers = [];

  function initMap() {
    var init_lat = <%= @farms.first.lat || 4.5076156 %>
    var init_lng = <%= @farms.first.lng || 114.4846021 %>
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: init_lat, lng: init_lng},
      zoom: 10
    });

    <% @farms.each do |farm| %>
      var marker = new google.maps.Marker({
        map: map,
        // draggable: true,
        animation: google.maps.Animation.DROP,
        position: {lat: <%= farm.lat %>, lng: <%= farm.lng %>}
      });

      google.maps.event.addListener(marker, 'click', function () {
        window.location.href = '/farms/<%= farm.id %>';
      });

    <% end %>

  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GGMAP_APP_KEY'] %>&callback=initMap"
async defer></script>

app/views/farms/index_orig.html.erb
<p id="notice"><%= notice %></p>

<h1>Farms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Farm code</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Layout</th>
      <th>Size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @farms.each do |farm| %>
      <tr>
        <td><%= farm.name %></td>
        <td><%= farm.farm_code %></td>
        <td><%= farm.lat %></td>
        <td><%= farm.lng %></td>
        <td><%= farm.layout %></td>
        <td><%= farm.size %></td>
        <td><%= link_to 'Show', farm %></td>
        <td><%= link_to 'Edit', edit_farm_path(farm) %></td>
        <td><%= link_to 'Destroy', farm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Farm', new_farm_path %>

app/views/farms/new.html.erb
<main id="farm-index" class="container text-center">

<div class="row header-container">
  <div class='col-md-12'>
    <h1>New Farm</h1>
  </div>
</div>

<div class="row content-container">
  <div class="col-md-12">
    <%= render 'form', farm: @farm %>
  </div>
</div>


<%= link_to 'Back', farms_path %>


</main>

app/views/farms/show.html.erb
<section id="farm-index" class="container text-center">

  <p id="notice"><%= notice %></p>
  
  <div class="row header-container">
    <h1><%= @farm.name %></h1>
  </div>


<section class="row content-container">
  <div class="row">
    <div class="col-md-6">

      <canvas id="farm-layout-show" width="400" height="400" style="border:1px solid #000000;">
      </canvas>

    </div>


    <div class="col-md-6 farm-show-info">

      <table class="table">
        <tr>
          <td><strong>Farm code</strong></td>
          <td><%= @farm.farm_code %></td>
        </tr>

        <tr>
          <td><strong>Latitude</strong></td>
          <td><%= @farm.lat %></td>
        </tr>

        <tr>
          <td><strong>Longitude</strong></td>
          <td><%= @farm.lng %></td>
        </tr>


        <tr>
          <td><strong>Size</strong></td>
          <td><%= @farm.size %></td>
        </tr>
      </table>

      <hr>

      <h3><%= "Sub Farm".pluralize(@farm.sub_farms.count) %></h3>
<!-- start tabs -->
      <ul class="nav nav-pills sub_farm_tabs">
        <li class='to-new-subfarm'><%= link_to raw('<i class="fa fa-plus" aria-hidden="true"></i>'), new_farm_sub_farm_path(@farm), class: 'btn', method: 'GET' %></li>
      </ul>

      <div class="tab-content sub_farm_content">
      </div>
<!-- end tabs -->

    </div>
  </div>
    <%= link_to 'Edit', edit_farm_path(@farm)%>, |
    <%= link_to 'Back', user_farms_path %>
</section>


</section>

<script>
  $(function(){

    var farm = document.getElementById('farm-layout-show');
    var ctx = farm.getContext("2d");

    <% @sub_farms.each do |subfarm| %>
      var a = $('<a data-toggle="pill" href="#subfarm<%= subfarm.id %>">').text('Subfarm <%= subfarm.id %>');
      var subfarm = $('<li>').append(a);
      subfarm.insertBefore('.to-new-subfarm');


      var crop = $('<tr>').html('<td><strong>Crop:</strong></td> <td><%= Crop.find(subfarm.crop_id).name %></td>');
      var size = $('<tr>').html('<td><strong>Size:</strong></td> <td><%= subfarm.size %></td>');
      var crop_w = $('<tr>').html('<td><strong>Crop weight:</strong></td> <td><%= subfarm.crop_weight %></td>');
      var est_yield = $('<tr>').html('<td><strong>Estimated Yield:</strong></td> <td><%= subfarm.calculate_yield %> kg/ha</td>');
      var start = $('<tr>').html('<td><strong>Start date:</strong></td> <td><%= subfarm.start_date %></td>');
      var harvest = $('<tr>').html('<td><strong>Harvest date:</strong></td> <td><%= subfarm.harvest_date %></td>');
      var btns = $('<tr>').html('<td></td><td class="text-right"><a class="btn btn-edit" data-method="get" href="/farms/<%= @farm.id %>/sub_farms/<%= subfarm.id %>/edit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>&nbsp<a  class="btn btn-delete" data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/farms/<%= @farm.id %>/sub_farms/<%= subfarm.id %>"><i class="fa fa-trash" aria-hidden="true"></i></a></td>');



      var content = $('<div class="tab-pane fade in active" id="subfarm<%= subfarm.id %>" >');
      var table = $('<table class="table table-responsive"></table>').append(crop).append(size).append(crop_w).append(est_yield).append(start).append(harvest).append(btns);
      content.append(table);
      $('.sub_farm_content').append(content);

      <% if subfarm.x and subfarm.y and subfarm.width and subfarm.height %>
        ctx.rect(<%= subfarm.x.to_f %>, <%= subfarm.y.to_f %>, <%= subfarm.width.to_f %>, <%= subfarm.height.to_f %>);
        ctx.stroke();
      <% end %>
    <% end %>
    $('.sub_farm_tabs li:first-child').addClass('active');
    $('.sub_farm_content').children('div:not(:first-child)').removeClass('in active');

  });
</script>