config/routes.rb
Rails.application.routes.draw do
  
  resources :dashboard, only: [:show]
  get 'report', to: 'report#index'

  resources :sessions, only: [:new, :create, :destroy]

  get 'user/farms', to: 'farms#user_show'
  post '/weather/forecast', to: 'weather_logs#get_weather'
  # get 'user/report', to: 'report#show'

  resources :weather_logs
  resources :sub_farm_activities
  resources :stocks
  resources :resources
  
  resources :crops
  resources :farms do
    resources :sub_farms
  end

  resources :users

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  has_many :farms
  
  has_secure_password

  # validates :username, uniqueness: true
  validates :password, length: { in: 6..20 }, on: :create
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @sub_farm_activity = SubFarmActivity.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password_digest, :firstname, :lastname, :email, :country, :city, :phone, :address)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_dashboard.html.erb
<div role="tabpanel" class="tab-pane" id="farm<%= farm.id %>">
  <div class="row">
    <div class="col-sm-8">
      <div class="col-md-12" id="<%= farm.id %>-timeline-container" class="farm-timeline">
      </div>
      <div class="col-sm-12" id="actions-container">
        <h3>Actions</h3>
        <div class="col-sm-3">
          <button type="button" class="btn btn-default btn-lg water-btn" data-toggle="modal" data-target="#actionsModal">
            <i class="fa fa-tint" aria-hidden="true"></i><span class="hidden-sm"> Water Farm</span>
          </button>
        </div>
        <div class="col-sm-3">
          <button type="button" class="btn btn-default btn-lg fertilize-btn">
            <i class="fa fa-medkit" aria-hidden="true"></i><span class="hidden-sm"> Fertilize Farm</span>
          </button>
        </div>
        <div class="col-sm-3">
          <button type="button" class="btn btn-default btn-lg chemical-btn">
            <i class="fa fa-flask" aria-hidden="true"></i><span class="hidden-sm"> Apply Chemicals</span>
          </button>
        </div>
        <div class="col-sm-3">
          <button type="button" class="btn btn-default btn-lg miscellaneous-btn">
            <i class="fa fa-flask" aria-hidden="true"></i><span class="hidden-sm"> Miscellaneous</span>
          </button>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="col-md-12" id="notifications-container">
        <div id="alert-not">
          <h3 id="align-nots">Notifications</h3>
            <table id="alert-table">
              <tr id="alert-date">
              <th>Date</th>
              </tr>
              <tr id="alert-rain">
              <th>Rain</th>
              </tr>
              <tr id="alert-wind">
              <th>Wind</th>
              </tr>
            </table>
        </div>
        <!-- <div class="panel panel-warning">
          <div class="panel-heading">Notifications</div>
          <div class="panel-body">
            <p><a href="#">High probability of Disease 0-MK!</a></p>
            <p><a href="#">Lots of raining coming in 4 days!</a></p>
            <p><a href="#">High probability of Disease 0-MK!</a></p>
            <p><a href="#">Lots of raining coming in 4 days!</a></p>
            <p><a href="#">High probability of Disease 0-MK!</a></p>
            <p><a href="#">Lots of raining coming in 4 days!</a></p>
          </div>
        </div> -->
      </div>
      <div class="col-md-12 farm-render-container">
        <h3>3D Render</h3>
        <canvas class="farmPlot"></canvas>
      </div>
    </div>
  </div>
</div>
<script>
  $(function() {
    createTimeline($("#<%= farm.id %>-timeline-container"));
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
      $($("#<%= farm.id %>-timeline-container")).highcharts().reflow();
    });
  });
</script>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :password_digest %>
    <%= f.text_field :password_digest %>
  </div>

  <div class="field">
    <%= f.label :firstname %>
    <%= f.text_field :firstname %>
  </div>

  <div class="field">
    <%= f.label :lastname %>
    <%= f.text_field :lastname %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :country %>
    <%= f.text_field :country %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_tablist.html.erb
<li role="presentation"><a href="#farm<%= farm.id %>" aria-controls="home" role="tab" data-toggle="tab"><%= farm.name %></a></li>

app/views/users/_watermodal.html.erb
<!-- Modal -->
<div class="modal fade" id="actionsModal" tabindex="-1" role="dialog" aria-labelledby="actionsModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="actionsModalLabel">Watered Plant</h4>
      </div>
      <div class="modal-body">
        <h1>New Sub Farm Activity</h1>
        <%= render 'sub_farm_activity/form', sub_farm_activity: @sub_farm_activity %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th>Country</th>
      <th>City</th>
      <th>Phone</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.country %></td>
        <td><%= user.city %></td>
        <td><%= user.phone %></td>
        <td><%= user.address %></td>
        <td><%= link_to 'log in', sessions_path(username: user.username), method: :post %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="container-fluid">
  <%= render "watermodal" %>

  <!-- Tab list -->
  <ul class="nav nav-tabs" role="tablist">
    <%= render partial: "users/tablist", collection: @user.farms, as: :farm %>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <%= render partial: "users/dashboard", collection: @user.farms, as: :farm %>
    <!-- <div role="tabpanel" class="tab-pane" id="farm2">This is profile</div> -->
  </div>
</div>

<script>
  $('.tab-pane').first().addClass('active');
  $('li[role=presentation]').first().addClass('active');
  run_render(document.querySelector('.farmPlot'));
</script>