config/routes.rb
Rails.application.routes.draw do
  
  resources :dashboard, only: [:show]
  get 'report', to: 'report#index'

  resources :sessions, only: [:new, :create, :destroy]

  get 'user/farms', to: 'farms#user_show'
  post '/weather/forecast', to: 'weather_logs#get_weather'
  # get 'user/report', to: 'report#show'

  resources :weather_logs
  resources :sub_farm_activities
  resources :stocks
  resources :resources
  
  resources :crops
  resources :farms do
    resources :sub_farms
  end

  resources :users

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/layouts/_nav.html.erb
<nav id="custom-navbar" class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><div class="col-xs-1 logo"><img class="img-responsive" src="<%= image_path('amber-logo.png') %>" /></div>Amber</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <% if(logged_in?) %>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dashboards <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% current_user.farms.each do |farm| %>
            <li><%= link_to farm.name, dashboard_path(farm), method: :get %>
            <% end %>
          </ul>
        </li>
        <li><%= link_to "Farm", '/user/farms' %></li>
        <li><%= link_to "Weather logs", weather_logs_path, method: :get %></li>
        <li><%= link_to "Report", report_path, method: :get %></li>
      </ul>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <!-- User menu -->
        <% if(logged_in?) %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", session_path("current"), method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Sign in", users_path() %></li>
        <% end %>
        <!-- End user menu -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amber - The Best Farm Management</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


    <script src="http://cdn.babylonjs.com/2-4/babylon.max.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- <link href='https://fonts.googleapis.com/css?family=Raleway:400,300,700' rel='stylesheet' type='text/css'> -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,700" rel="stylesheet">


    <!-- Highcharts -->
    <script src="https://code.highcharts.com/highcharts.js"></script>

  </head>

  <body>
    <%= render 'layouts/nav' %>
    
    <%= yield %>
    
  <footer class="footer" id="footer-homepage">
    <div>
      <ul id="footer-content">
      <li><a style="color:grey;">Terms&Conditions</a></li>
      <li>&copy;Amber</li>
      </ul>
    </div>
  </footer>
  </body>
</html>

app/views/layouts/index.html.erb
<div class="container-fluid">
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#farm1" aria-controls="home" role="tab" data-toggle="tab">Farm 1</a></li>
    <li role="presentation"><a href="#farm2" aria-controls="profile" role="tab" data-toggle="tab">Farm 2</a></li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="farm1">
      <div class="row">
        <div class="col-xs-6 col-md-5" id="farm-render-container">
          <canvas id="farmPlot"></canvas>
          <!-- <img src="./assets/images/floating-island.png" class="img-responsive" /> -->
        </div>
        <div class="col-xs-6 col-md-5" id="notifications-container">
          <div class="panel panel-warning">
            <div class="panel-heading">Notifications</div>
            <div class="panel-body">
              <p><a href="#">High probability of Disease 0-MK!</a></p>
              <p><a href="#">Lots of raining coming in 4 days!</a></p>
            </div>
          </div>
        </div>
        <div class="col-md-2" id="actions-container">
          <button type="button" class="btn btn-default btn-lg">
            <i class="fa fa-tint" aria-hidden="true"></i> Water Farm
          </button>
          <button type="button" class="btn btn-default btn-lg">
            <i class="fa fa-medkit" aria-hidden="true"></i> Fertilize Farm
          </button>
          <button type="button" class="btn btn-default btn-lg">
            <i class="fa fa-flask" aria-hidden="true"></i> Apply Chemicals
          </button>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12" id="timeline-container">
        fsaf
        </div>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane" id="farm2">This is profile</div>
  </div>
</div>